######################################################################
# Automatically generated by qmake (2.00a) Wed Apr 26 13:54:05 2006
######################################################################


#---------------------------------------------------------------------
#Global Definitions
#---------------------------------------------------------------------
QT += sql
TEMPLATE = app
TARGET = hms
CONFIG += release

INCLUDEPATH += . src/ src/common


#---------------------------------------------------------------------
#Search Paths
#---------------------------------------------------------------------
DEPENDPATH += . \
              src\common \
              src\dbmgr \
              src\functionroom \
              src\maint \
              src\mainwindow \
              src\pmm \
              src\rio \
              src\security \
              src\tour \
              src\functionroom\ui \
              src\maint\ui \
              src\mainwindow\ui \
              src\pmm\ui \
              src\rio\ui \
              src\security\ui \
              src\tour\ui



#---------------------------------------------------------------------
# Common Module
#---------------------------------------------------------------------

HEADERS += src/common/common.h \
           src/common/fakevalues.h \
           src/common/us_state_combo_box.h \
           src/common/filterserialnum.h \
           src/common/version.h

SOURCES += src/common/us_state_combo_box.cpp \
           src/common/filterserialnum.cpp



#---------------------------------------------------------------------
# Sudha's Modules
#---------------------------------------------------------------------

HEADERS += src/dbmgr/db_mgr.h

SOURCES += src/dbmgr/db_mgr.cpp



#---------------------------------------------------------------------
# Savitha's Modules
#---------------------------------------------------------------------

HEADERS += src/pmm/hotel_base.h \
           src/pmm/owner_base.h \
           src/pmm/room_base.h \
           src/pmm/room_types_base.h \
	   src/pmm/rates_increase.h \
	   src/pmm/tablecombobox.h \
	   src/pmm/restaurant_info.h \
	   src/pmm/tables_info.h \
	   src/pmm/func_room_info.h 

SOURCES += src/pmm/hotel_base.cpp \
           src/pmm/owner_base.cpp \
           src/pmm/room_base.cpp \
           src/pmm/room_types_base.cpp \
	   src/pmm/rates_increase.cpp \
	   src/pmm/tablecombobox.cpp \
           src/pmm/restaurant_info.cpp \
	   src/pmm/tables_info.cpp \
	   src/pmm/func_room_info.cpp


FORMS += src/pmm/ui/hotel_info.ui

#THESE FILES FAIL TO BUILD as of 2006-05-04 jjm
#
# src/pmm/hotel_info.h
# src/pmm/hotel_info.cpp
#



#---------------------------------------------------------------------
# Lakshmi's Modules
#---------------------------------------------------------------------

#HEADERS += src/security/security_emp_details.h \
 #         src/security/security_emp_details_base.h

#SOURCES += src/security/security_emp_details.cpp \
#            src/security/security_emp_details_base.cpp

#FORMS += src/security/ui/security_emp_details.ui



#---------------------------------------------------------------------
# Prasoona's Modules
#---------------------------------------------------------------------

HEADERS +=  \
	    src/functionroom/function_room_base.h \	
            src/tour/tour_info.h\
            src/restaurant/table_reservation_base.h\
	    src/restaurant/table_waitlist_base.h
            	

SOURCES +=  \
            src/functionroom/function_room_base.cpp \
            src/tour/tour_info.cpp \
            src/restaurant/table_reservation_base.cpp\
	    src/restaurant/table_waitlist_base.cpp

FORMS += src/functionroom/ui/function_room.ui \
	 src/functionroom/ui/function_roomdialog.ui \
         src/tour/ui/tour_information.ui\
	 src/restaurant/ui/tableReservation.ui \
         src/restaurant/ui/tableReserveDialog.ui 
        

#Fails to Compile: 2006-05-06
# src/tour/tour_info_base.cpp
# src/tour/tour_info_base.h
# src/functionroom/function_room_dialog.cpp
# src/functionroom/function_room_dialog.h
# src/functionroom/function_room.cpp
# src/functionroom/function_room.h
# src/restaurant/table_reservation.h
# src/restaurant/table_reservation.cpp
# src/restaurant/table_reservedialog.cpp\


#---------------------------------------------------------------------
# Warren's Modules
#---------------------------------------------------------------------




#---------------------------------------------------------------------
# John's Modules
#---------------------------------------------------------------------

FORMS += src/mainwindow/ui/about.ui \
         src/mainwindow/ui/default_view.ui \
         src/mainwindow/ui/login.ui \
         src/mainwindow/ui/main_window.ui \
         src/mainwindow/ui/softlinks.ui \
         src/rio/ui/checkin_confirm.ui \
         src/rio/ui/checkout_confirm.ui \
         src/rio/ui/customer_edit.ui \
         src/rio/ui/guest_edit.ui \
         src/rio/ui/room_resv_chooser.ui \
         src/rio/ui/room_resv_edit.ui \
	 src/rio/ui/checkin_confirm.ui \
	 src/rio/ui/checkout_confirm.ui



HEADERS += src/mainwindow/about_ui.h \
           src/mainwindow/browserlaunch.h \
           src/mainwindow/default_view_ui.h \
           src/mainwindow/login_ui.h \
           src/mainwindow/main_window.h \
           src/mainwindow/softlinks_ui.h \
           src/mainwindow/stub_security.h \
           src/rio/customer.h \
           src/rio/customer_base.h \
           src/rio/guest.h \
	   src/rio/customer.h \
           src/rio/guest_base.h \
           src/rio/room_reservation.h \
           src/rio/room_reservation_base.h \
           src/rio/room_reservation_log.h \
           src/rio/room_resv_chooser_ui.h \
           src/rio/room_resv_edit_ui.h \
           src/rio/guest_edit_ui.h \
	   src/rio/customer_edit_ui.h \
	   src/rio/checkin_confirm_ui.h \
	   src/rio/checkout_confirm_ui.h

SOURCES += src/mainwindow/about_ui.cpp \
           src/mainwindow/browserlaunch.cpp \
           src/mainwindow/default_view_ui.cpp \
           src/mainwindow/login_ui.cpp \
           src/mainwindow/softlinks_ui.cpp \
           src/mainwindow/stub_security.cpp \
           src/rio/customer_base.cpp \
           src/rio/guest_base.cpp \
           src/rio/room_reservation_base.cpp \
           src/rio/room_reservation_log.cpp \
           src/rio/room_reservation.cpp \
           src/rio/guest.cpp \
	   src/rio/customer.cpp \
           src/rio/guest_edit_ui.cpp \
	   src/rio/customer_edit_ui.cpp \
	   src/rio/checkin_confirm_ui.cpp \
	   src/rio/checkout_confirm_ui.cpp \
	   src/rio/room_resv_edit_ui.cpp \
           src/rio/room_resv_chooser_ui.cpp 


SOURCES += src/mainwindow/main_window.cpp



#---------------------------------------------------------------------
# Main Routine
#---------------------------------------------------------------------
SOURCES += src/main.cpp



#---------------------------------------------------------------------
# Platform Specific Definitions
#---------------------------------------------------------------------


unix {
    OBJECTS_DIR=.obj/
    MOC_DIR=.obj/
    UI_DIR=.obj/
    RCC_DIR=.obj/
    DEFINES+=DATABASE='"QMYSQL"'
}


win32 {
  CONFIG += console
}



